drop table if exists region;

create table region
(
    region_id   int generated by default as identity primary key,
    region_name   varchar not null UNIQUE,
    latitude double precision,
    longitude double precision
);


insert into region(region_name, latitude, longitude)
values ('Самарская область', 53.90917246733839, 50.616143207431726),
       ('Иркутская область', 58.3608798853652, 106.7071647562136);